# Generated by Django 6.0.4 on 2026-05-22 13:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0003_candidate_certifications'),
    ]

    operations = [
        migrations.AddField(
            model_name='companyprofile',
            name='company_size',
            field=models.CharField(blank=True, max_length=60),
        ),
        migrations.AddField(
            model_name='companyprofile',
            name='description',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='companyprofile',
            name='industry',
            field=models.CharField(blank=True, max_length=120),
        ),
        migrations.AddField(
            model_name='companyprofile',
            name='website',
            field=models.URLField(blank=True, max_length=300),
        ),
        migrations.AlterField(
            model_name='candidateprofile',
            name='education_level',
            field=models.CharField(blank=True, choices=[('high_school', 'High School'), ('bachelor', 'Bachelor'), ('master', 'Master'), ('phd', 'PhD'), ('bootcamp', 'Bootcamp / Certification'), ('other', 'Other')], max_length=120),
        ),
    ]
