# Generated by Django 5.2.13 on 2026-05-22 13:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0004_companyprofile_company_size_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='companyprofile',
            name='is_approved',
            field=models.BooleanField(default=False),
        ),
    ]
