# Generated by Django 5.2.13 on 2026-05-22 16:24

import app1.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0005_companyprofile_is_approved'),
    ]

    operations = [
        migrations.AddField(
            model_name='companyprofile',
            name='background_image',
            field=models.ImageField(blank=True, upload_to=app1.models.company_profile_file_path),
        ),
        migrations.AddField(
            model_name='companyprofile',
            name='logo',
            field=models.ImageField(blank=True, upload_to=app1.models.company_profile_file_path),
        ),
    ]
