# Generated by Django 5.2.13 on 2026-05-22 17:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0006_company_logo_background'),
    ]

    operations = [
        migrations.AlterField(
            model_name='joboffer',
            name='contract_type',
            field=models.CharField(choices=[('cdi', 'CDI (Permanent)'), ('cdd', 'CDD (Fixed-term)'), ('anapec', 'ANAPEC (Insertion)'), ('stage_pre', 'Stage Pré-embauche'), ('stage_obs', "Stage d'observation"), ('freelance', 'Freelance / Auto-entrepreneur'), ('ctt', 'CTT (Interim)')], max_length=40),
        ),
        migrations.AlterField(
            model_name='joboffer',
            name='job_type',
            field=models.CharField(choices=[('full_time', 'Full-time'), ('part_time', 'Part-time'), ('internship', 'Internship / Stage'), ('alternance', 'Alternance / Apprentissage'), ('freelance', 'Freelance / Mission'), ('shift', 'Shift Work')], max_length=40),
        ),
    ]
